## Data on UK arms exports, from CAAT (Campaign Against Arms Trade)

**last update: 09.54**

> Latest release, August 2026: https://github.com/caatdata/uk-arms-export-data
>
> See that repo's README for a description of the datasets
>
> See also their FAQs: https://caat.org.uk/data/exports-uk/faq

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action = 'ignore', category = Warning)

In [3]:
# the github folder now sits in the same directory as my local notebook

!ls arms_aug_2026

footnotes-licence.csv          README.markdown
footnotes-region.csv           refusal-criteria.csv
incorporation-destinations.csv trade-sources.csv
items.csv                      values.csv
ratings.csv

### Eight datasets

> load dataset and assign to a variable name
> 
> print the shape (rows, columns) of the dataset
>
> show head or sample for the top (n) number of rows, or a sample (n) number of rows

In [20]:
items = pd.read_csv('arms_aug_2026/items.csv')
print(items.shape)
items.head(3)

(649301, 19)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation
0,1,1,2008-01-02,NaN,SIEL,Austria,AT,1,0,NaN,0,0,0.0,0.0,NaN,NBC filters,NaN,ML7,military
1,2,2,2008-01-02,NaN,SIEL,Germany,DE,0,0,NaN,1,0,0.0,0.0,NaN,biological agent detection equipment,NaN,ML7,military
2,3,3,2008-01-02,NaN,SIEL,Hong Kong Special Administrative Region,HK,0,0,NaN,0,0,0.0,0.0,NaN,equipment employing cryptography,NaN,5A002,dual-use

In [19]:
values = pd.read_csv('arms_aug_2026/values.csv')
print(values.shape)
values.head(3)

(223698, 17)

,licence_cohort_id,date,type,destination,iso2,incorporation,refused,unused,licence_count,temporary_count,permanent_count,revoked_count,appeal_count,revocation_date_count,rating,regulation,value
0,1,2008-01-02,SIEL,Austria,AT,1,0,NaN,1,0,0,0.0,0.0,0,ML7,military,14720
1,2,2008-01-02,SIEL,Germany,DE,0,0,NaN,1,1,0,0.0,0.0,0,ML7,military,3000
2,3,2008-01-02,SIEL,Hong Kong Special Administrative Region,HK,0,0,NaN,1,0,0,0.0,0.0,0,5A002,dual-use,10750000

In [18]:
ratings = pd.read_csv('arms_aug_2026/ratings.csv')
print(ratings.shape)
ratings.head(3)

(319, 4)

,rating,military,short_description,full_description
0,ML1,1,Small arms,Smooth bore weapons with a calibre of less tha...
1,ML2,1,"Light weapons, artillery",Smooth bore weapons with a calibre of 20mm or ...
2,ML3,1,Ammunition,Ammunition and fuze setting devices

In [17]:
ts = pd.read_csv('arms_aug_2026/trade-sources.csv')
print(ts.shape)
ts.head(3)

(1, 4)

   licence_cohort_id   source iso2  licence_count
0                 27  Germany   DE        44927.0

In [16]:
rs = pd.read_csv('arms_aug_2026/refusal-criteria.csv')
print(rs.shape)
rs.sample(3)

(4474, 3)

,licence_cohort_id,criterion,description
2127,128819,7,Risk of diversion or re-export to undesirable ...
4150,219621,5,"National security of the UK, of allies, EU Mem..."
2461,146622,7,Risk of diversion or re-export to undesirable ...

In [15]:
inc = pd.read_csv('arms_aug_2026/incorporation-destinations.csv')
print(inc.shape)
inc.sample(3)

(192018, 3)

        licence_cohort_id destination iso2
105142             151438     Finland   FI
33921               74991        Oman   OM
191540             229143   Australia   AU

In [21]:
fr = pd.read_csv('arms_aug_2026/footnotes-region.csv')
print(fr.shape)
fr.sample(3)

(267, 2)

,name,text
63,Democratic Republic of Congo,"Following the adoption of UNSCR 1807 (2008), t..."
68,Democratic Republic of Congo,"Following the adoption of UNSCR 1807 (2008), t..."
155,Myanmar,A comprehensive ban on the provision of all ar...

In [22]:
fl = pd.read_csv('arms_aug_2026/footnotes-region.csv')
print(fl.shape)
fl.sample(3)

(267, 2)

,name,text
199,Somalia,Arms trade sanctions against Somalia were adop...
234,Sudan,UN Security Council resolution 1556 (2004) est...
93,Hong Kong Special Administrative Region,A declaration by the European Council meeting ...

### Filtering!

In [26]:
# show a filtered version with just Austria
items[items.destination == 'Austria'].head(3)

# save the filtered df
aut = items[items.destination == 'Austria']

# export the csv (goes to the same directory as this notebook)
aut.to_csv("austria_df.csv", index = False)

In [30]:
# check data type on cols - is the 'date' column really datetime? No

items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649301 entries, 0 to 649300
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   licence_id           649301 non-null  int64
 1   licence_cohort_id    649301 non-null  int64
 2   date                 649301 non-null  object
 3   date_start           0 non-null       float64
 4   type                 649301 non-null  object
 5   destination          649301 non-null  object
 6   iso2                 640437 non-null  object
 7   incorporation        649301 non-null  int64
 8   refused              649301 non-null  int64
 9   unused               3 non-null       object
 10  temporary            649301 non-null  int64
 11  permanent            649301 non-null  int64
 12  revoked              294185 non-null  float64
 13  appeal               292537 non-null  float64
 14  revocation_date      2307 non-null    object
 15  item                 649301 non-null  object
 16  quantity             19994 non-null   float64
 17  implicit_rating      649301 non-null  object
 18  implicit_regulation  649301 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 94.1+ MB

In [33]:
# make a new 'year' col from the date col
items["year"] = items["date"].str[:4]
items.tail(2)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation,year
649299,251761,226729,2026-03-31,NaN,SIEL,France,FR,0,0,NaN,0,0,0.0,0.0,NaN,technology for nuclear reactors,NaN,0E001,dual-use,2026
649300,251762,226730,2026-03-31,NaN,SIEL,Russia,RU,0,0,NaN,0,0,0.0,0.0,NaN,G7 Dependency and further goods list goods and...,NaN,RUS,dual-use,2026

In [37]:
# filter for years

# list of years we want
years = ['2024', '2025', '2026']

# filter against list
items[items.year.isin(years)]

# assign to a variable
threeyears = items[items.year.isin(years)]

# how many rows now?
print(len(threeyears))

69495

In [39]:
threeyears.head(3)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation,year
579806,237705,213876,2024-01-02,NaN,SIEL,Angola,AO,0,0,NaN,1,0,0.0,0.0,NaN,submersible equipment,NaN,8A002,dual-use,2024
579807,237706,213877,2024-01-02,NaN,SITCL,Azerbaijan,AZ,0,1,NaN,0,0,NaN,NaN,NaN,military parachutes,NaN,ML10,military,2024
579808,237707,213878,2024-01-02,NaN,SIEL,Canada,CA,0,0,NaN,0,0,0.0,0.0,NaN,toxins,NaN,1C351,dual-use,2024