## Data on UK arms exports, from CAAT (Campaign Against Arms Trade)

**last update: 11.19**

> Latest release, August 2026: https://github.com/caatdata/uk-arms-export-data
>
> See that repo's README for a description of the datasets
>
> See also their FAQs: https://caat.org.uk/data/exports-uk/faq

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action = 'ignore', category = Warning)

In [3]:
# the github folder now sits in the same directory as my local notebook

!ls arms_aug_2026

footnotes-licence.csv          README.markdown
footnotes-region.csv           refusal-criteria.csv
incorporation-destinations.csv trade-sources.csv
items.csv                      values.csv
ratings.csv

### Eight datasets

> load dataset and assign to a variable name
> 
> print the shape (rows, columns) of the dataset
>
> show head or sample for the top (n) number of rows, or a sample (n) number of rows

In [85]:
items = pd.read_csv('arms_aug_2026/items.csv')
print(items.shape)
items.head(3)

(649301, 19)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation
0,1,1,2008-01-02,NaN,SIEL,Austria,AT,1,0,NaN,0,0,0.0,0.0,NaN,NBC filters,NaN,ML7,military
1,2,2,2008-01-02,NaN,SIEL,Germany,DE,0,0,NaN,1,0,0.0,0.0,NaN,biological agent detection equipment,NaN,ML7,military
2,3,3,2008-01-02,NaN,SIEL,Hong Kong Special Administrative Region,HK,0,0,NaN,0,0,0.0,0.0,NaN,equipment employing cryptography,NaN,5A002,dual-use

In [19]:
values = pd.read_csv('arms_aug_2026/values.csv')
print(values.shape)
values.head(3)

(223698, 17)

,licence_cohort_id,date,type,destination,iso2,incorporation,refused,unused,licence_count,temporary_count,permanent_count,revoked_count,appeal_count,revocation_date_count,rating,regulation,value
0,1,2008-01-02,SIEL,Austria,AT,1,0,NaN,1,0,0,0.0,0.0,0,ML7,military,14720
1,2,2008-01-02,SIEL,Germany,DE,0,0,NaN,1,1,0,0.0,0.0,0,ML7,military,3000
2,3,2008-01-02,SIEL,Hong Kong Special Administrative Region,HK,0,0,NaN,1,0,0,0.0,0.0,0,5A002,dual-use,10750000

In [18]:
ratings = pd.read_csv('arms_aug_2026/ratings.csv')
print(ratings.shape)
ratings.head(3)

(319, 4)

,rating,military,short_description,full_description
0,ML1,1,Small arms,Smooth bore weapons with a calibre of less tha...
1,ML2,1,"Light weapons, artillery",Smooth bore weapons with a calibre of 20mm or ...
2,ML3,1,Ammunition,Ammunition and fuze setting devices

In [17]:
ts = pd.read_csv('arms_aug_2026/trade-sources.csv')
print(ts.shape)
ts.head(3)

(1, 4)

   licence_cohort_id   source iso2  licence_count
0                 27  Germany   DE        44927.0

In [16]:
rs = pd.read_csv('arms_aug_2026/refusal-criteria.csv')
print(rs.shape)
rs.sample(3)

(4474, 3)

,licence_cohort_id,criterion,description
2127,128819,7,Risk of diversion or re-export to undesirable ...
4150,219621,5,"National security of the UK, of allies, EU Mem..."
2461,146622,7,Risk of diversion or re-export to undesirable ...

In [86]:
inc = pd.read_csv('arms_aug_2026/incorporation-destinations.csv')
print(inc.shape)
inc.sample(3)

(192018, 3)

       licence_cohort_id destination iso2
94173             139697     Algeria   DZ
70207             113352      Kuwait   KW
99506             145629       Syria   SY

In [21]:
fr = pd.read_csv('arms_aug_2026/footnotes-region.csv')
print(fr.shape)
fr.sample(3)

(267, 2)

,name,text
63,Democratic Republic of Congo,"Following the adoption of UNSCR 1807 (2008), t..."
68,Democratic Republic of Congo,"Following the adoption of UNSCR 1807 (2008), t..."
155,Myanmar,A comprehensive ban on the provision of all ar...

In [22]:
fl = pd.read_csv('arms_aug_2026/footnotes-region.csv')
print(fl.shape)
fl.sample(3)

(267, 2)

,name,text
199,Somalia,Arms trade sanctions against Somalia were adop...
234,Sudan,UN Security Council resolution 1556 (2004) est...
93,Hong Kong Special Administrative Region,A declaration by the European Council meeting ...

### Filtering!

In [40]:
# show a filtered version with just Austria
items[items.destination == 'Austria'].head(3)

# save the filtered df
aut = items[items.destination == 'Austria']

# export the csv (goes to the same directory as this notebook)
aut.to_csv("austria_df.csv", index = False)

In [30]:
# check data type on cols - is the 'date' column really datetime? No

items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649301 entries, 0 to 649300
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   licence_id           649301 non-null  int64
 1   licence_cohort_id    649301 non-null  int64
 2   date                 649301 non-null  object
 3   date_start           0 non-null       float64
 4   type                 649301 non-null  object
 5   destination          649301 non-null  object
 6   iso2                 640437 non-null  object
 7   incorporation        649301 non-null  int64
 8   refused              649301 non-null  int64
 9   unused               3 non-null       object
 10  temporary            649301 non-null  int64
 11  permanent            649301 non-null  int64
 12  revoked              294185 non-null  float64
 13  appeal               292537 non-null  float64
 14  revocation_date      2307 non-null    object
 15  item                 649301 non-null  object
 16  quantity             19994 non-null   float64
 17  implicit_rating      649301 non-null  object
 18  implicit_regulation  649301 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 94.1+ MB

In [33]:
# make a new 'year' col from the date col
items["year"] = items["date"].str[:4]
items.tail(2)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation,year
649299,251761,226729,2026-03-31,NaN,SIEL,France,FR,0,0,NaN,0,0,0.0,0.0,NaN,technology for nuclear reactors,NaN,0E001,dual-use,2026
649300,251762,226730,2026-03-31,NaN,SIEL,Russia,RU,0,0,NaN,0,0,0.0,0.0,NaN,G7 Dependency and further goods list goods and...,NaN,RUS,dual-use,2026

In [37]:
# filter for years

# list of years we want
years = ['2024', '2025', '2026']

# filter against list
items[items.year.isin(years)]

# assign to a variable
threeyears = items[items.year.isin(years)]

# how many rows now?
print(len(threeyears))

69495

In [39]:
threeyears.head(3)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation,year
579806,237705,213876,2024-01-02,NaN,SIEL,Angola,AO,0,0,NaN,1,0,0.0,0.0,NaN,submersible equipment,NaN,8A002,dual-use,2024
579807,237706,213877,2024-01-02,NaN,SITCL,Azerbaijan,AZ,0,1,NaN,0,0,NaN,NaN,NaN,military parachutes,NaN,ML10,military,2024
579808,237707,213878,2024-01-02,NaN,SIEL,Canada,CA,0,0,NaN,0,0,0.0,0.0,NaN,toxins,NaN,1C351,dual-use,2024

In [41]:
items

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation,year
0,1,1,2008-01-02,NaN,SIEL,Austria,AT,1,0,NaN,0,0,0.0,0.0,NaN,NBC filters,NaN,ML7,military,2008
1,2,2,2008-01-02,NaN,SIEL,Germany,DE,0,0,NaN,1,0,0.0,0.0,NaN,biological agent detection equipment,NaN,ML7,military,2008
2,3,3,2008-01-02,NaN,SIEL,Hong Kong Special Administrative Region,HK,0,0,NaN,0,0,0.0,0.0,NaN,equipment employing cryptography,NaN,5A002,dual-use,2008
3,4,4,2008-01-02,NaN,SIEL,Italy,IT,1,0,NaN,0,0,0.0,0.0,NaN,components for military utility helicopters,NaN,ML10,military,2008
4,5,5,2008-01-02,NaN,SIEL,Philippines,PH,0,0,NaN,0,0,0.0,0.0,NaN,general military aircraft components,NaN,ML10,military,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649296,251759,226728,2026-03-30,NaN,SIEL,United Arab Emirates,AE,0,0,NaN,1,0,0.0,0.0,NaN,targeting equipment,NaN,ML5,military,2026
649297,251759,226728,2026-03-30,NaN,SIEL,United Arab Emirates,AE,0,0,NaN,1,0,0.0,0.0,NaN,weapon night sights,NaN,ML1,military,2026
649298,251760,226729,2026-03-31,NaN,SIEL,France,FR,0,0,NaN,0,0,0.0,0.0,NaN,technology for nuclear reactor fuel element fa...,NaN,0E001,dual-use,2026
649299,251761,226729,2026-03-31,NaN,SIEL,France,FR,0,0,NaN,0,0,0.0,0.0,NaN,technology for nuclear reactors,NaN,0E001,dual-use,2026
649300,251762,226730,2026-03-31,NaN,SIEL,Russia,RU,0,0,NaN,0,0,0.0,0.0,NaN,G7 Dependency and further goods list goods and...,NaN,RUS,dual-use,2026

### The 'onward' problem: incorporation destinations

- Filter the incorporation-destinations csv for 'Israel' as the destination. There are 2663 cohort ids that include Israel
- Make a list of all the licence_cohort_id numbers. We'll call the list 'LCI'. There are 3573 (so not all these rows concern Israel it seems)
- Create a new column in the 'items' df called 'can include ISR' with 1s and 0s.

In [87]:
# filter the incorporation-destinations df (inc) and print number of rows (len)

print(len(inc[inc.destination == 'Israel']))
inc[inc.destination == 'Israel'].head(4)

2663

     licence_cohort_id destination iso2
152                334      Israel   IL
234                609      Israel   IL
273                691      Israel   IL
351               1087      Israel   IL

In [88]:
# Example: show me just rows with licence_cohort_id 195753. This cohort id includes several countries. 

print(len(items[items.licence_cohort_id == 195753]))
items[items.licence_cohort_id == 195753].head(3)

12

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation
507203,217303,195753,2022-07-11,NaN,SIEL,Italy,IT,1,0,NaN,0,0,0.0,0.0,NaN,components for equipment for the production of...,NaN,ML22,military
507204,217303,195753,2022-07-11,NaN,SIEL,Italy,IT,1,0,NaN,0,0,0.0,0.0,NaN,technology for equipment for the production of...,NaN,ML18,military
507205,217303,195753,2022-07-11,NaN,SIEL,Italy,IT,1,0,NaN,0,0,0.0,0.0,NaN,components for equipment for the production of...,NaN,ML22,military

In [90]:
# in the INC dataset how many different countries appear in the LICENCE_COHORT_ID number 195753. 

# if you want the countries as a list
# inc[inc.licence_cohort_id == 195753].destination.tolist()

# otherwise
inc[inc.licence_cohort_id == 195753]

        licence_cohort_id           destination iso2
133948             195753             Australia   AU
133949             195753               Austria   AT
133950             195753               Belgium   BE
133951             195753                 Egypt   EG
133952             195753               Finland   FI
133953             195753                France   FR
133954             195753               Germany   DE
133955             195753                Greece   GR
133956             195753                 India   IN
133957             195753                Israel   IL
133958             195753                Jordan   JO
133959             195753                Kuwait   KW
133960             195753           Netherlands   NL
133961             195753           New Zealand   NZ
133962             195753                Norway   NO
133963             195753                  Oman   OM
133964             195753              Pakistan   PK
133965             195753                Poland   PL
133966             195753                 Qatar   QA
133967             195753          Saudi Arabia   SA
133968             195753               Senegal   SN
133969             195753             Singapore   SG
133970             195753                 Spain   ES
133971             195753                Sweden   SE
133972             195753           Switzerland   CH
133973             195753          Turkmenistan   TM
133974             195753  United Arab Emirates   AE
133975             195753        United Kingdom   GB

In [91]:
# get all the cohort ids in INC in which Israel appears.

lci = list(inc[inc.destination == 'Israel'].licence_cohort_id)
lci

[334,
 609,
 691,
 1087,
 4475,
 5884,
 7755,
 9792,
 9820,
 9953,
 12947,
 13078,
 13560,
 13765,
 13887,
 14321,
 14989,
 15084,
 15179,
 15458,
 16074,
 16161,
 16211,
 16427,
 16573,
 16923,
 17316,
 17621,
 17770,
 17964,
 18845,
 22181,
 22345,
 22373,
 22399,
 22431,
 22467,
 22512,
 22638,
 22897,
 23004,
 23042,
 23095,
 23096,
 25993,
 26039,
 26066,
 26231,
 29477,
 29767,
 29823,
 29941,
 30053,
 30146,
 30220,
 30348,
 30538,
 30605,
 30669,
 30853,
 30934,
 31092,
 31192,
 31576,
 31623,
 31683,
 31732,
 31794,
 32051,
 32133,
 32356,
 32411,
 32459,
 32550,
 32640,
 32706,
 32776,
 32875,
 33070,
 33117,
 33184,
 33313,
 33405,
 33496,
 33561,
 33798,
 34264,
 34929,
 35334,
 35387,
 35447,
 35563,
 35627,
 35764,
 35918,
 36024,
 36151,
 36385,
 36729,
 36731,
 37452,
 40866,
 42199,
 42979,
 43158,
 43402,
 43645,
 43674,
 43709,
 43845,
 44310,
 44439,
 44450,
 44517,
 44737,
 45057,
 45264,
 45327,
 45640,
 45701,
 46362,
 46387,
 48209,
 50332,
 50684,
 50799,
 50973,
 51207,
 51244,
 51297,
 51437,
 51503,
 51572,
 51644,
 51771,
 51973,
 52225,
 52344,
 52392,
 52514,
 52557,
 52616,
 52765,
 52807,
 52939,
 53288,
 53590,
 53824,
 53937,
 54011,
 54259,
 54346,
 54437,
 54661,
 54864,
 54964,
 55131,
 55220,
 55325,
 55326,
 55547,
 55602,
 55713,
 55768,
 55819,
 55925,
 56007,
 56087,
 56164,
 56239,
 56633,
 59384,
 59499,
 59559,
 59621,
 59680,
 59715,
 59768,
 59936,
 60256,
 60455,
 60603,
 60658,
 60704,
 60858,
 60903,
 61117,
 61527,
 61675,
 61681,
 61729,
 61765,
 61813,
 61856,
 61900,
 62007,
 62022,
 62117,
 62140,
 62244,
 62335,
 62371,
 62427,
 62515,
 62602,
 62653,
 62710,
 62749,
 62808,
 62822,
 62875,
 62886,
 62944,
 63010,
 63026,
 63075,
 63088,
 63134,
 63146,
 63196,
 63210,
 63283,
 63295,
 63376,
 63433,
 63484,
 63596,
 63658,
 63709,
 63721,
 63736,
 63793,
 63852,
 63918,
 63932,
 63992,
 64086,
 64132,
 64185,
 64217,
 64279,
 64289,
 64323,
 64347,
 64358,
 64402,
 64424,
 64475,
 64488,
 64545,
 64586,
 64651,
 64772,
 64849,
 64947,
 64985,
 65124,
 65184,
 65202,
 65271,
 65272,
 65334,
 65396,
 65435,
 65443,
 65507,
 65549,
 65610,
 65652,
 65659,
 65751,
 65800,
 65808,
 65851,
 65861,
 65910,
 65969,
 65980,
 66032,
 66061,
 66068,
 66114,
 66124,
 66239,
 66253,
 66371,
 66562,
 66626,
 66698,
 66749,
 66803,
 66875,
 66903,
 66922,
 66973,
 67031,
 67067,
 67072,
 67132,
 67172,
 67224,
 67275,
 67341,
 67391,
 67428,
 67471,
 67512,
 67627,
 67698,
 67749,
 67809,
 67842,
 67871,
 67930,
 68156,
 68252,
 68356,
 68428,
 68592,
 68659,
 68720,
 68761,
 68825,
 68893,
 68939,
 68985,
 69030,
 69107,
 69166,
 69221,
 69277,
 69334,
 69415,
 69457,
 69460,
 69497,
 69506,
 69573,
 69630,
 69673,
 69679,
 69738,
 69795,
 69802,
 69910,
 69923,
 69969,
 70015,
 70083,
 70092,
 70149,
 70217,
 70230,
 70271,
 70282,
 70324,
 70401,
 70507,
 70522,
 70574,
 70610,
 70725,
 70778,
 70821,
 70991,
 71058,
 71115,
 71199,
 71230,
 71328,
 71393,
 71401,
 71422,
 71442,
 71598,
 71657,
 71926,
 72168,
 72603,
 72676,
 72849,
 73053,
 73107,
 73177,
 73271,
 73468,
 73528,
 73638,
 73702,
 73804,
 73856,
 73896,
 73953,
 74043,
 74105,
 74153,
 74238,
 74288,
 74343,
 74393,
 74450,
 74506,
 74547,
 74554,
 74596,
 74637,
 74710,
 74726,
 74807,
 74859,
 74876,
 75031,
 75050,
 75075,
 75088,
 75136,
 75184,
 75192,
 75241,
 75242,
 75251,
 75298,
 75314,
 75394,
 75402,
 75479,
 75531,
 75589,
 75635,
 75735,
 75774,
 75795,
 75864,
 75912,
 75925,
 75956,
 75959,
 75995,
 76081,
 76093,
 76144,
 76283,
 76401,
 76430,
 76576,
 76655,
 76717,
 76757,
 76791,
 76802,
 76824,
 76858,
 76869,
 76925,
 76942,
 76964,
 77007,
 77017,
 77035,
 77072,
 77134,
 77167,
 77218,
 77283,
 77306,
 77361,
 77445,
 77451,
 77464,
 77506,
 77519,
 77567,
 77600,
 77643,
 77674,
 77702,
 77714,
 77738,
 77768,
 77777,
 77825,
 77898,
 77921,
 77972,
 78050,
 78061,
 78119,
 78185,
 78246,
 78255,
 78286,
 78296,
 78404,
 78449,
 78460,
 78513,
 78576,
 78646,
 78697,
 78747,
 78760,
 78814,
 78820,
 78858,
 78904,
 78910,
 78944,
 78981,
 78984,
 79027,
 79068,
 79083,
 79087,
 79131,
 79184,
 79207,
 79235,
 79256,
 79267,
 79307,
 79310,
 79329,
 79356,
 79407,
 79417,
 79437,
 79459,
 79468,
 79525,
 79529,
 79573,
 79645,
 79659,
 79710,
 79732,
 79736,
 79775,
 79805,
 79902,
 79975,
 80015,
 80040,
 80042,
 80049,
 80107,
 80153,
 80182,
 80199,
 80243,
 80279,
 80308,
 80328,
 80339,
 80384,
 80404,
 80416,
 80448,
 80463,
 80468,
 80496,
 80504,
 80589,
 80644,
 80655,
 80659,
 80723,
 80764,
 80770,
 80868,
 80918,
 81059,
 81099,
 81139,
 81191,
 81231,
 81288,
 81376,
 81525,
 81578,
 81607,
 81635,
 81660,
 81706,
 81773,
 81819,
 81856,
 81887,
 81911,
 81934,
 82016,
 82058,
 82085,
 82110,
 82183,
 82258,
 82286,
 82310,
 82494,
 82522,
 82553,
 82600,
 82602,
 82627,
 82725,
 82765,
 82792,
 82872,
 82961,
 82993,
 83018,
 83061,
 83098,
 83153,
 83177,
 83297,
 83308,
 83352,
 83372,
 86804,
 86842,
 86940,
 86996,
 87048,
 87089,
 87217,
 87272,
 87374,
 87402,
 87456,
 87540,
 87670,
 87857,
 87903,
 87958,
 87983,
 88316,
 88374,
 88417,
 88460,
 88491,
 88676,
 88844,
 88959,
 89210,
 89284,
 89334,
 89427,
 89505,
 89572,
 89650,
 89717,
 89774,
 89870,
 90236,
 90268,
 90308,
 90398,
 90442,
 90515,
 90574,
 90622,
 90679,
 91230,
 91250,
 91251,
 91286,
 91300,
 91318,
 91351,
 91374,
 91386,
 91391,
 91427,
 91482,
 91565,
 91650,
 91777,
 91813,
 91872,
 91879,
 91995,
 92036,
 92095,
 92118,
 92132,
 92135,
 92157,
 92177,
 92183,
 92237,
 92248,
 92286,
 92306,
 92313,
 92379,
 92398,
 92406,
 92447,
 92478,
 92488,
 92589,
 92849,
 92894,
 92903,
 92941,
 92960,
 92994,
 93005,
 93032,
 93048,
 93104,
 93232,
 93249,
 93286,
 93306,
 93350,
 93360,
 93365,
 93392,
 93401,
 93469,
 93480,
 93528,
 93609,
 93628,
 93680,
 93754,
 93780,
 93787,
 93812,
 93842,
 93859,
 93904,
 93953,
 94114,
 94186,
 94291,
 94418,
 94518,
 94616,
 94642,
 94688,
 94713,
 94725,
 94785,
 94820,
 94880,
 94913,
 94961,
 94992,
 95011,
 95025,
 95078,
 95092,
 95103,
 95150,
 95161,
 95216,
 95396,
 95407,
 95486,
 95543,
 95613,
 95703,
 95797,
 95854,
 95879,
 95905,
 96015,
 96049,
 96078,
 96098,
 96146,
 96163,
 96175,
 96179,
 96214,
 96267,
 96285,
 96383,
 96386,
 96415,
 96443,
 96501,
 96515,
 96564,
 96578,
 96600,
 96616,
 96617,
 96630,
 96653,
 96663,
 96674,
 96709,
 96737,
 96779,
 96799,
 96868,
 96886,
 96900,
 96948,
 96960,
 96963,
 96975,
 97001,
 97021,
 97031,
 97064,
 97066,
 97078,
 97097,
 97167,
 97175,
 97218,
 97220,
 97232,
 97285,
 97288,
 97297,
 97341,
 97350,
 97397,
 97464,
 97517,
 97519,
 97525,
 97560,
 97567,
 97580,
 97612,
 97624,
 97686,
 97739,
 97743,
 97810,
 97825,
 97827,
 97844,
 97914,
 97919,
 97937,
 97941,
 97944,
 97951,
 98013,
 98079,
 98082,
 98093,
 98159,
 98256,
 98290,
 98307,
 98385,
 98421,
 98433,
 98487,
 98523,
 98541,
 98580,
 98597,
 98609,
 98644,
 98668,
 98724,
 98745,
 98778,
 98799,
 98821,
 98853,
 98876,
 99022,
 99037,
 99074,
 99111,
 99152,
 99177,
 99186,
 99233,
 99291,
 99333,
 99346,
 99367,
 99408,
 99418,
 99472,
 99507,
 99522,
 99538,
 99572,
 99612,
 99625,
 99688,
 99746,
 99772,
 99774,
 99785,
 99812,
 99852,
 99886,
 99933,
 100083,
 100179,
 100199,
 100218,
 100329,
 100387,
 100412,
 100464,
 100566,
 100627,
 100647,
 100852,
 100904,
 100975,
 101017,
 101083,
 101107,
 101171,
 101234,
 101273,
 101337,
 101385,
 101423,
 101462,
 101527,
 101543,
 101557,
 101586,
 101629,
 101661,
 101699,
 101729,
 101765,
 101831,
 101857,
 101898,
 101903,
 102006,
 102031,
 102053,
 102136,
 102156,
 102192,
 102193,
 102273,
 102280,
 102316,
 102345,
 102451,
 102500,
 102536,
 102556,
 102587,
 102605,
 102623,
 102732,
 102846,
 102874,
 102902,
 102924,
 102967,
 103008,
 103044,
 103067,
 103096,
 103171,
 103199,
 103246,
 103248,
 103272,
 103376,
 103389,
 103410,
 103436,
 103450,
 103525,
 103646,
 103654,
 103678,
 103689,
 103692,
 103717,
 103730,
 103769,
 103782,
 103788,
 103816,
 103839,
 103848,
 103885,
 103982,
 104104,
 104112,
 104155,
 104285,
 104312,
 104358,
 104434,
 104507,
 ...]

In [92]:
# make new column that flags all the rows with the selected licence_cohort_ids

items["can_include_ISR"] = items["licence_cohort_id"].isin(lci).astype(int)

In [93]:
items.head(4)

,licence_id,licence_cohort_id,date,date_start,type,destination,iso2,incorporation,refused,unused,temporary,permanent,revoked,appeal,revocation_date,item,quantity,implicit_rating,implicit_regulation,can_include_ISR
0,1,1,2008-01-02,NaN,SIEL,Austria,AT,1,0,NaN,0,0,0.0,0.0,NaN,NBC filters,NaN,ML7,military,0
1,2,2,2008-01-02,NaN,SIEL,Germany,DE,0,0,NaN,1,0,0.0,0.0,NaN,biological agent detection equipment,NaN,ML7,military,0
2,3,3,2008-01-02,NaN,SIEL,Hong Kong Special Administrative Region,HK,0,0,NaN,0,0,0.0,0.0,NaN,equipment employing cryptography,NaN,5A002,dual-use,0
3,4,4,2008-01-02,NaN,SIEL,Italy,IT,1,0,NaN,0,0,0.0,0.0,NaN,components for military utility helicopters,NaN,ML10,military,0

In [94]:
# where israel is included as a possible final destination, what is the initial country?

items[items.can_include_ISR == 1].destination.value_counts()

destination
Italy                       1410
United States of America    1002
Germany                      934
France                       128
Spain                         33
Canada                        16
Poland                        13
Netherlands                    9
Romania                        5
Turkey                         5
Mexico                         4
India                          3
Greece                         3
Singapore                      2
Czech Republic                 2
Australia                      1
Philippines                    1
Slovakia                       1
China                          1
Name: count, dtype: int64